#!/bin/bash


alias docker='sudo docker'
alias docker-compose='sudo docker-compose'
export PS1='\[\033[01;32m\]\u\[\033[01;00m\]@\[\033[01;33m\]\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '

# include directory colors
[ -e "$HOME/.dircolors" ] && DIR_COLORS="$HOME/.dircolors"
[ -e "$DIR_COLORS" ] || DIR_COLORS=""
eval "`dircolors -b $DIR_COLORS`"

screen -r >& /dev/null && \
    echo "You were automatically logged into an open screen session." && \
    echo -e "You have now been logged out of \033[01;33m$(hostname)\033[00m entirely" && \
    exit
